ignore-dirs:
  - config
  - scripts
ignores: 
  - "~"
  - "@testing-library/jest-dom"
  - babel-jest
  - babel-plugin-istanbul
  - core-js
  - coveralls
  - depcheck
  - env-cmd
  - http
  - if-env
  - istanbul-lib-coverage
  - jsonlint
  - lcov-result-merger
  - license-checker
  - mocha-junit-reporter
  - netlify-cli
  - regenerator-runtime
  - sass
  - socket.io
  - socket.io-client
  - stylelint
  - stylelint-config-standard
  - svglint
  - svgo
  - tldrlegal
  - wait-on
  - env-cmd
  - if-env